# Server settings (ServerProperties)
#端口
server:
  port: 8082
  address: 127.0.0.1
  #server.sessionTimeout=30
  #访问路径名称
  servlet:
    context-path: /bootbuliding


## 自定义属性配置加载
com:
  cundream:
    title: Spring Boot教程--Lison
    name: Lison SpringBoot 系统构建
    desc: ${com.cundream.name}
    value: ${random.value}

